apiVersion: v1
kind: Namespace
metadata:
  name: registry
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/node-selector: node-role.kubernetes.io/infra=
    scheduler.alpha.kubernetes.io/defaultTorelations: '[{"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/infra"},{"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/infra"}]'
