apiVersion: v1
kind: Namespace
metadata:
  name: registry
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/node-selector: node-role.kubernetes.io/infra=
    scheduler.alpha.kubernetes.io/defaultTorelations: '[{"operator":"Equal","value":"","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"},{"operator":"Equal","value":"","effect":"NoExecute","key":"node-role.kubernetes.io/infra"}]'
