apiVersion: operators.coreos.com/v1alpha1
kind: OperatorGroup
metadata:
  name: quay-operatorgroup
  namespace: registry
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
  - registry
