apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: registry
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable-3.15
  name: quay-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
